spring.application.name=library

spring.datasource.url=jdbc:postgresql://localhost:5432/perpustakaan
spring.datasource.username=perpus
spring.datasource.password=perpus123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-message=always
